version: "3"

services:
  vpn:
    image: tailscale/tailscale
    network_mode: host
    volumes:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_HOSTNAME=alpha1
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTH_KEY=tskey-auth-kYuToTWuNU11CNTRL-FShS9cgacXbF6Y66aw9iXbYFiZTZibNc
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
