version: "3.8"

services:
  vpn:
    image: linuxserver/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=valentin-schaar.de
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto
    volumes:
      - vpn:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1


volumes:
  vpn:
