version: "3.8"

services:
  cloud_db:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --skip-innodb-read-only-compressed
    restart: unless-stopped
    networks:
      - cloud
    volumes:
      - cloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  cloud_cache:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - cloud
    command: redis-server --requirepass test

  cloud:
    image: nextcloud
    restart: unless-stopped
    depends_on:
      - cloud_db
      - cloud_cache
    environment:
      - REDIS_HOST=cloud_cache
      - REDIS_HOST_PASSWORD=test
      - MYSQL_HOST=cloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=nextcloud
    volumes:
      - cloud:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloud.entrypoints=websecure"
      - "traefik.http.routers.cloud.rule=Host(`cloud.valentin-schaar.de`)"
      - "traefik.http.routers.cloud.tls=true"
      - "traefik.http.routers.cloud.tls.certresolver=proxy_cert"
      - "traefik.http.services.cloud.loadbalancer.server.port=80"
      - "traefik.http.services.cloud.loadbalancer.passHostHeader=true"
      - "traefik.http.routers.cloud.middlewares=nc-header,nc-rep"
      - "traefik.http.middlewares.nc-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nc-header.headers.customResponseHeaders.Strict-Transport-Security=15552000"
    networks:
      - proxy
      - cloud

networks:
  proxy:
  cloud:

volumes:
  cloud:
  cloud_db:
