version: "3.8"

services:
  cloud:
    image: nextcloud:latest
    restart: unless-stopped
    links:
      - cloud_db
    volumes:
      - cloud_data:/var/www/html
    networks:
      - proxy
      - cloud
    environment:
      - VIRTUAL_HOST=cloud.valentin-schaar.de
      - LETSENCRYPT_HOST=cloud.valentin-schaar.de

      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=cloud_db
  
  cloud_db:
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - cloud_db_data:/var/lib/mysql
    networks:
      - cloud
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud


volumes:
  cloud_data:
  cloud_db_data:


networks:
  cloud:
