version: "3.8"

services:
  cloud:
    image: nextcloud:latest
    restart: unless-stopped
    links:
      - cloud_db
    volumes:
      - cloud:/var/www/html
    networks:
      - proxy
      - cloud
    environment:
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=cloud_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloud.rule=Host(`cloud.valentin-schaar.de`)"
      - "traefik.http.routers.cloud.entrypoints=websecure"
      - "traefik.http.routers.cloud.tls.certresolver=proxy_cert"
  
  cloud_db:
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - cloud_db:/var/lib/mysql
    networks:
      - cloud
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud


volumes:
  cloud:
  cloud_db:


networks:
  proxy:
  cloud:
