version: "3.8"

services:

  # Cloud storage
  
  cloud:
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - cloud_data:/var/www/html
    depends_on:
      - cloud_db
    environment:
      - VIRTUAL_HOST=cloud.valentin-schaar.de
      - LETSENCRYPT_HOST=cloud.valentin-schaar.de

      - POSTGRES_HOST=cloud_db
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing123

      - NEXTCLOUD_ADMIN_USER=root
      - NEXTCLOUD_ADMIN_PASSWORD=root

  cloud_db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - cloud_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing123


volumes:
  cloud_data:
  cloud_db_data:
