version: "3.8"

services:

  # Cloud storage

  cloud:
    container_name: cloud
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.cloud
    volumes:
      - cloud_data:/var/www/html
    depends_on:
      - cloud_db
    environment:
      - VIRTUAL_HOST=cloud.valentin-schaar.de
      - LETSENCRYPT_HOST=cloud.valentin-schaar.de
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.valentin-schaar.de,cloud,cloud_db,valentin-schaar.de

  cloud_db:
    container_name: cloud_db
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.cloud_db
    volumes:
        - cloud_db_data:/var/lib/mysql


volumes:
  cloud_data:
  cloud_db_data:
