FROM guacamole/guacamole:latest

ENV GUACD_HOSTNAME=remote_proxy

ENV MYSQL_HOSTNAME=remote_db
ENV MYSQL_DATABASE=guacamole
ENV MYSQL_USER=guacamole
ENV MYSQL_PASSWORD=",X3K#)ZtN1tYf\\%J#3D-"

EXPOSE 8080
