version: "3"

services:

  # Proxy and web page

  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "80:80"
    depends_on:
      - cloud

  # Cloud storage

  cloud:
    container_name: cloud
    build:
      context: .
      dockerfile: Dockerfile.cloud
    volumes:
      - cloud_data:/var/www/html
    depends_on:
      - cloud_db

  cloud_db:
    container_name: cloud_db
    build:
      context: .
      dockerfile: Dockerfile.cloud_db
    volumes:
        - cloud_db_data:/var/lib/mysql

volumes:
  cloud_data:
  cloud_db_data:
