FROM guacamole/guacamole:latest

ENV GUACD_HOSTNAME=remote_proxy

ENV MYSQL_HOSTNAME=remote_db
ENV MYSQL_DATABASE=guacamole_db
ENV MYSQL_USER=guacamole_user
ENV MYSQL_PASSWORD="iePjcNNhvY8XqXPw74eK"

EXPOSE 8080
