version: "3.8"

services:

  # Proxy and web page

  proxy:
    container_name: proxy
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cert/conf:/etc/letsencrypt
      - ./cert/www:/var/www/certbot
    depends_on:
      - cloud

  cert:
    container_name: cert
    restart: unless-stopped
    image: certbot/certbot
    volumes:
      - ./cert/conf:/etc/letsencrypt
      - ./cert/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --non-interactive --agree-tos --register-unsafely-without-email -d valentin-schaar.de -d www.valentin-schaar.de -d cloud.valentin-schaar.de -d remote.valentin-schaar.de #--force-renewal

  # Cloud storage
  
  remote_windows:
    container_name: remote_windows
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.remote_windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006 # For installation
    stop_grace_period: 2m
    volumes:
      - remote_windows_data:/storage

  cloud:
    container_name: cloud
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.cloud
    volumes:
      - cloud_data:/var/www/html
    depends_on:
      - cloud_db

  cloud_db:
    container_name: cloud_db
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.cloud_db
    volumes:
        - cloud_db_data:/var/lib/mysql

  # Remote desktop

  
  remote_proxy:
    container_name: remote_proxy
    image: guacamole/guacd
    restart: always

  remote_db:
    container_name: remote_db
    build:
      context: .
      dockerfile: Dockerfile.remote_db
    restart: always
    volumes:
      - remote_db_data:/var/lib/postgresql/data:Z

  remote:
    container_name: remote
    depends_on:
      - remote_proxy
      - remote_db
    build:
      context: .
      dockerfile: Dockerfile.remote
    restart: always
 

volumes:
  cert_conf_data:
  cert_www_data:

  cloud_data:
  cloud_db_data:

  remote_windows_data:
  remote_db_data:
