version: "3"

services:

  # Proxy and web page

  proxy:
    container_name: proxy
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cert_conf_data:/etc/letsencrypt
      - cert_www_data:/var/www/certbot
    depends_on:
      - cloud

  cert:
    container_name: cert
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.cert
    depends_on:
      - proxy
    volumes:
      - cert_conf_data:/etc/letsencrypt
      - cert_www_data:/var/www/certbot

  # Cloud storage

  cloud:
    container_name: cloud
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.cloud
    volumes:
      - cloud_data:/var/www/html
    depends_on:
      - cloud_db

  cloud_db:
    container_name: cloud_db
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.cloud_db
    volumes:
        - cloud_db_data:/var/lib/mysql

  # Remote desktop
  
  remote_proxy:
    container_name: remote_proxy
    image: guacamole/guacd
    restart: always

  remote_db:
    container_name: remote_db
    build:
      context: .
      dockerfile: Dockerfile.remote_db
    restart: always
    volumes:
      - remote_db_data:/var/lib/postgresql/data:Z

  remote:
    container_name: remote
    depends_on:
      - remote_proxy
      - remote_db
    build:
      context: .
      dockerfile: Dockerfile.remote
    restart: always
  

volumes:
  cert_conf_data:
  cert_www_data:

  cloud_data:
  cloud_db_data:

  remote_db_data:
