version: '3'

services:
  remote_proxy:
    container_name: remote_proxy
    image: guacamole/guacd
    restart: always

  remote_db:
    container_name: remote_db
      #environment:
      #PGDATA: /var/lib/postgresql/data/guacamole
      #POSTGRES_DB: guacamole_db
      #POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      #POSTGRES_USER: guacamole_user
      #iimage: postgres:15.2-alpine
    restart: always
    volumes:
      - ./remote_db:/docker-entrypoint-initdb.d:z
      - remote_db_data:/var/lib/postgresql/data:Z

  remote:
    container_name: remote
    depends_on:
      - remote_proxy
      - remote_db
    environment:
      GUACD_HOSTNAME: remote_proxy
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_HOSTNAME: remote_db
      POSTGRESQL_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRESQL_USER: guacamole_user
    image: guacamole/guacamole
    ports:
    - 8080:8080/tcp
    restart: always

volumes:
  remote_db_data:
