version: "3.8"

include:
  - ./web/docker-compose.yml
  - ./cloud/docker-compose.yml
  - ./remote/docker-compose.yml

services:
  proxy:
    image: traefik
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      #- "--api.insecure=true"
      #- "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

      - "--certificatesresolvers.proxy_cert.acme.tlschallenge=true"
      - "--certificatesresolvers.proxy_cert.acme.email=valentin.schaar@web.de"
      - "--certificatesresolvers.proxy_cert.acme.storage=/letsencrypt/acme.json"
    networks:
      - proxy
    ports:
      - 443:443
      - 80:80
    volumes:
      - proxy_certs:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  proxy_certs:

networks:
  proxy:
