version: "3.8"

include:
  - ./web/docker-compose.yml
  - ./cloud/docker-compose.yml
  - ./remote/docker-compose.yml

services:
  proxy:
    image: nginxproxy/nginx-proxy:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
      - proxy_certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
    environment:
      - ENABLE_IPV6=true

  proxy_acme:
    image: nginxproxy/acme-companion
    restart: unless-stopped
    volumes_from:
      - proxy
    volumes:
      - proxy_certs:/etc/nginx/certs:rw
      - proxy_acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy


volumes:
  proxy_vhost:
  proxy_html:
  proxy_certs:
  proxy_acme:


networks:
  proxy:
