version: "3.8"

include:
  - ./web/docker-compose.yml
  - ./cloud/docker-compose.yml
  - ./remote/docker-compose.yml

services:

  # Proxy

  proxy:
    image: nginxproxy/nginx-proxy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - proxy_vhost_data:/etc/nginx/vhost.d
      - proxy_html_data:/usr/share/nginx/html
      - proxy_certs_data:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
    environment:
      - ENABLE_IPV6=true

  proxy_acme:
    image: nginxproxy/acme-companion
    volumes_from:
      - proxy
    volumes:
      - proxy_certs_data:/etc/nginx/certs:rw
      - proxy_acme_data:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    #environment:
      #- DEFAULT_EMAIL=valentin.schaar@web.de  # Optional


volumes:
  proxy_vhost_data:
  proxy_html_data:
  proxy_certs_data:
  proxy_acme_data:


networks:
  proxy:
