version: "3.8"

services:

  # Remote desktop
  
  remote:
    restart: unless-stopped
    depends_on:
      - remote_proxy
      - remote_db
    build:
      context: .
      dockerfile: Dockerfile.remote
    networks:
      - proxy
      - remote
    environment:
      - VIRTUAL_HOST=remote.valentin-schaar.de
      - LETSENCRYPT_HOST=remote.valentin-schaar.de

  remote_proxy:
    restart: always
    image: guacamole/guacd
    networks:
      - remote

  remote_db:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.remote_db
    networks:
      - remote
    volumes:
      - ./remote_db/:/docker-entrypoint-initdb.d:z
      - remote_db_data:/var/lib/postgresql/data:Z

  remote_windows:
    image: dockurr/windows:latest
    restart: unless-stopped
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    expose:
      - 8006
    volumes:
      - remote_windows_data:/storage
    networks:
      - proxy
    environment:
      - VIRTUAL_PORT=8006
      - VIRTUAL_HOST=windows.remote.valentin-schaar.de
      - LETSENCRYPT_HOST=windows.remote.valentin-schaar.de

      - VERSION=win11
      - RAM_SIZE=4G
      - CPU_CORES=4
      - DISK_SIZE=128G


volumes:
  remote_db_data:
  remote_windows_data:


networks:
  remote:
