version: "3.8"

services:
  remote:
    restart: unless-stopped
    depends_on:
      - remote_daemon
      - remote_db
    build:
      context: .
      dockerfile: Dockerfile.remote
    networks:
      - proxy
      - remote
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remote.rule=Host(`remote.valentin-schaar.de`)"
      - "traefik.http.routers.remote.entrypoints=websecure"
      - "traefik.http.routers.remote.tls.certresolver=proxy_cert"


  remote_daemon:
    image: guacamole/guacd
    restart: unless-stopped
    networks:
      - remote

  remote_db:
    build:
      context: .
      dockerfile: Dockerfile.remote_db
    restart: unless-stopped
    networks:
      - remote
    volumes:
      - ./remote_db/:/docker-entrypoint-initdb.d:z
      - remote_db:/var/lib/postgresql/data:Z

  remote_windows:
    image: dockurr/windows:latest
    restart: unless-stopped
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    ports:
      - 3389:3389
    expose:
      - 8006
    volumes:
      - remote_windows:/storage
    networks:
      - proxy
    environment:
      - VIRTUAL_PORT=8006
      - VIRTUAL_HOST=windows.remote.valentin-schaar.de
      - LETSENCRYPT_HOST=windows.remote.valentin-schaar.de

      - VERSION=win11
      - RAM_SIZE=12G
      - CPU_CORES=5
      - DISK_SIZE=128G


volumes:
  remote_db:
  remote_windows:


networks:
  proxy:
  remote:
