version: "3.8"

services:
  web:
    image: nginx
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`www.valentin-schaar.de`) || Host(`valentin-schaar.de`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=proxy_cert"
