version: "3.8"

services:
  web:
    image: nginx
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=www.valentin-schaar.de,valentin-schaar.de
      - LETSENCRYPT_HOST=www.valentin-schaar.de,valentin-schaar.de
